export enum ErrorCodes {
  ADMIN_NOT_CONFIGURED = 'ADMIN_NOT_CONFIGURED',
  DATABASE_ERROR = 'DATABASE_ERROR',
  DTO_VALIDATION_ERROR = 'DTO_VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
  INFRA_FAILURE = 'INFRA_FAILURE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  REDIS_ERROR = 'REDIS_ERROR',
  TODO_NOT_FOUND = 'TODO_NOT_FOUND',
  USER_INSUFFICIENT_PERMISSIONS = 'USER_INSUFFICIENT_PERMISSIONS',
  USER_IS_NOT_AUTHORIZED = 'USER_IS_NOT_AUTHORIZED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
